name: Build and Push EE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ansible-builder
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image with buildx
        run: |
          docker buildx create --use --name ibmpower-ee-builder
          ansible-builder create -f execution-environment.yml
          docker buildx build \
            --push \
            --platform=linux/amd64,linux/arm64 \
            --tag ghcr.io/kmkamyk/ibmpower-ee:latest \
            context

