name: Build and Push EE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible-builder
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder docker

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create context with Dockerfile
        run: ansible-builder create -f execution-environment.yml

      - name: Build and push EE image
        run: |
          docker buildx create --use --name ibmpower-ee-builder
          docker buildx build \
            --push \
            --platform=linux/amd64,linux/arm64 \
            --tag ghcr.io/kmkamyk/ibmpower-ee:latest \
            ./context
