name: Build EE Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible-builder
        run: pip install ansible-builder docker

      - name: Build EE
        run: ansible-builder build -t ghcr.io/${{ github.repository }}:latest -f execution-environment.yml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push EE Image
        run: docker push ghcr.io/${{ github.repository }}:latest
